apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.13.0
apiServer:
  extraArgs:
    enable-admission-plugins: AlwaysPullImages,DefaultStorageClass,PodSecurityPolicy,LimitRanger,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
    token-auth-file: /etc/kubernetes/auth/tokens.csv
  extraVolumes:
  - name: tokens
    hostPath: /etc/kubernetes/auth
    mountPath: /etc/kubernetes/auth
networking:
  podSubnet: 10.244.0.0/16
